[workspace]
resolver = "2"

exclude = [
    "./examples"
]

members = [
    "aper",
    "aper/aper_derive*",
    "aper-stateroom",
    "aper-serve",
    "aper-yew",
    "aper-websocket-client",
    "site/doctests",
]
