[package]
name = "counter-service"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aper-stateroom = { path="../../../aper-stateroom" }
aper = { path="../../../aper" }
stateroom-wasm = { version="0.2.3" }
counter-common = { path="../common" }
