[package]
name = "timer-common"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aper = { path="../../../aper" }
chrono = "0.4.19"
serde = { version = "1.0.127", features = ["derive"] }
