[package]
name = "aper-serve"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/drifting-in-space/aper"

[dependencies]
aper = {path = "../aper"}
aper-jamsocket = {path = "../aper-jamsocket"}
env_logger = "0.9.0"
jamsocket-server = { git = "https://github.com/jamsocket/jamsocket", version="0.1.5" }
log = "0.4.14"
